Feature: ArchivedWarikanGroupDTOの実装
ADS-Gang-of-Five/warikan-roulette pull request #124
Opened 2024-01-31 17:08 UTC by Masaki-JP

DTOの実装に関しておかしな点があればChange Requestください。

- feat: SeisanDTOの作成
- feat: ArchivedWarikanGroupDTO
- change: ViewDataをArchivedWarikanGroupDTOに置換

2024-02-01 12:43 UTC, Se1getsu requested changes
修正前に比べてデータ構造が読みやすくなりましたね👍

さらに改善できる点として、2箇所お伝えします。

## DTO生成のロジックの切り出し

現状 `getArchivedWarikanGroupDTO()` 内には、以下の3種類の処理が書かれていて読みづらくなっています。
1. `SeisanDTO`の生成処理
2. `ArchivedWarikanGroupDTO` の生成処理
3. プロパティ `archivedWarikanGroupDTO` の更新処理

通常、**Viewから直接呼び出されるViewModelのメソッド内の処理は簡潔であるべき**です。1の処理は`SeisanDTO`の、2の処理は`ArchivedWarikanGroupDTO`のstatic funcに切り出してあげると簡潔になると思います。
そうすれば今回のリファクタ、`ViewData`という抽象的な名前やタプルで管理していたデータを各Entity専用の型として定義したことが活きてくると思います。

（補足）
static funcで生成するなら、DTOの生成に必要なUseCaseはMethod Injectionで渡すことになるでしょう。
static funcで生成する方法 は Factoryパターンで生成する方法 を簡略化したものなので、真面目にやるならFactoryのinitに注入する形になりますが、面倒なのでやりません。

## 別のファイルで定義

現状このファイルでしか使ってないからDTOをViewModelのファイル内で定義してるのだと思いますが、このオブジェクトはもはや**このViewからは自立して再利用可能な状態**になっているので、それぞれ専用のファイルを作ってあげた方がいいと思います。
それに、こういう型の定義が上の方にどんどん溜まると、このファイルの主であるはずのViewModelのコードがどんどん下の方に流れていってしまうので避けたいです。

2024-02-01 12:56 UTC, sasasan03 approved these changes
LGTM

2024-02-03 06:03 UTC, sasasan03 approved these changes
LGTM

2024-02-03 07:22 UTC, sasasan03 approved these changes
LGTM

2024-02-03 07:29 UTC, sasasan03 approved these changes
LGTM

2024-02-09 13:24 UTC, closed without merging